name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Install libpcap
      run: apt-get update && apt-get install libpcap

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
